# Generated by Django 4.1.7 on 2023-04-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_grupo_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='ficha',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ficha'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.perfil'),
        ),
    ]
